filter:
    excluded_paths:
        - 'tests/'
        - 'vendor/'

tools:
    external_code_coverage:
        timeout: 600 # default is 300 seconds, travis build can take more than that

build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run --enable-security-analysis
