filter:
    excluded_paths:
        - 'tests/'
        - 'vendor/'

tools:
    external_code_coverage: true

build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run --enable-security-analysis
