site_name: CfdiUtils
site_description: Librería de utilerías comunes para trabajar con PHP y CFDI 3.2 & 3.3 (México)

theme: readthedocs

markdown_extensions:
    - toc:
        permalink: 
    - admonition
    - def_list
    - fenced_code

copyright: Copyright &copy; MIT License 2017 - 2018 Carlos C Soto & contibutors

